[mcpsec_severity_lookup]
filename = mcpsec_severity.csv
min_matches = 1
max_matches = 1
default_match = Unknown

[mcpsec_owasp_category_lookup]
filename = mcpsec_owasp_categories.csv
min_matches = 1
max_matches = 1
default_match = Unknown

[mcpsec_extract_rule_id]
REGEX = "uid"\s*:\s*"(MCP-\d+)"
FORMAT = rule_id::$1

[mcpsec_extract_severity]
REGEX = "severity_id"\s*:\s*(\d+)
FORMAT = severity_id::$1
